name: DNS Block&Redirect Configurer cron task

on:
  schedule:
    - cron: '30 1 * * *' # 04:30 MSK (01:30 UTC)
  workflow_dispatch:

concurrency:
  group: dnsconf-scheduled-or-manual-sync
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DNS
    timeout-minutes: 75

    env:
      DNS: ${{ vars.DNS }}
      BLOCK: ${{ vars.BLOCK }}
      REDIRECT: ${{ vars.REDIRECT }}
      EXCLUDE_REDIRECT: ${{ vars.EXCLUDE_REDIRECT }}
      NEXTDNS_REWRITE_EXCLUSIONS: ${{ vars.NEXTDNS_REWRITE_EXCLUSIONS }}

      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      REDIRECT_TARGET: ${{ secrets.REDIRECT_TARGET }}
      PROXY_PREVIOUS_REDIRECT_TARGETS: ${{ secrets.PROXY_PREVIOUS_REDIRECT_TARGETS }}
      PROXY_VPS_ROOT_PASSWORD: ${{ secrets.PROXY_VPS_ROOT_PASSWORD }}
      PROXY_VPS_SSH_KNOWN_HOSTS: ${{ secrets.PROXY_VPS_SSH_KNOWN_HOSTS }}

      TZ: Europe/Moscow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run application
        run: |
          echo "Starting application..."
          java --enable-preview -jar target/*.jar
